### ISSUE TITLE
Authenticated requests

### ISSUE THREAD

**Issue by ghost** [paulirish/github-email#10]
Note that the rate limits can be exceeded. As such, perhaps it would be possible to allow configuring an API key for authenticated requests.

**Comment by paulirish** [comment]
sgtm. usually i see use of a GITHUB_TOKEN env variable, so that'd be my preference.

**Comment by paulirish** [comment]
Ah. I just merged https://github.com/paulirish/github-email/pull/8 which partially deals with this.

We can reuse the same token for the other requests.

**Comment by paulirish** [comment]
So #8 only uses a token for the first call.

"Emails from recent commits" and "Emails from owned-repo recent activity" could use this access token if it's set.

**Comment by paulirish** [comment]
Put a PR up for the second part: https://github.com/paulirish/github-email/pull/11
