### ISSUE TITLE
Color formatting makes it hard to read in dark mode in macOS Terminal

### ISSUE THREAD

**Issue by philfreo** [paulirish/github-email#20]
<img width="293" alt="Screenshot 2019-10-21 16 10 38" src="https://user-images.githubusercontent.com/97612/67239522-5fccd880-f41d-11e9-843d-fd44e09fa758.png">

I assume it's only difficult to read here because this package is trying to be fancy with colors?

Just using default macOS Terminal app but with the OS-level Dark Mode enabled.

**Comment by paulirish** [comment]
thanks for reporting. fixed  in 452dae6
