### ISSUE TITLE
Some user return no email

### ISSUE THREAD

**Issue by zhongjiajie** [paulirish/github-email#22]
Ex: https://github.com/liboren
After I install by `npm install --global github-email` and then run `github-email liboren` it return as below
![](https://i.loli.net/2020/02/17/qmhKRjSAFlTOa48.png)
but when I follow [this article](https://www.sourcecon.com/how-to-find-almost-any-github-users-email-address-2-0) I could find user email in [this patch](https://github.com/liboren/WeRobot/commit/79a6f60b89db5ee6a3f6e0555953afbdb3830972.patch).

So could we get user email in those without email in their profile？

**Comment by tianshanghong** [comment]
There are some words in that section of "Email on GitHub." They are "hidden" because of the black background. You probably need to add your GitHub token in your environment variables to get those emails.
