### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by zcorpan** [paulirish/github-email#23]
When using `github-email` I got an email from GitHub:

> On (today) your personal access token (redacted) using curl/7.54.0 was used as part of a query parameter to access an endpoint through the GitHub API:
>
> (redacted url)
>
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
>
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
>
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

**Comment by paulirish** [comment]
Thanks. Just fixed this. Released a 1.1.2 with the fix.

update: did a few more fixes and shipped a 1.1.3
