### ISSUE TITLE
Unable to fetch public email

### ISSUE THREAD

**Issue by fpg1503** [paulirish/github-email#7]
I ran `github-email fpg1503` but the script was not able to fetch my public github email:

**Expected output:**
```
Email on GitHub
fpg1503+spamOptOut@@@@@@@@@@gmail.com

Email on npm
fpg1503@@@@@@@gmail.com

Emails from recent commits
...

Emails from owned-repo recent activity
...
```

**Actual Output**
```
Email on GitHub

Email on npm
fpg1503@@@@@@@@gmail.com

Emails from recent commits
...

Emails from owned-repo recent activity
...
```

-----

_EDIT(paulirish)_: edited out all the other folks' emails.

**Comment by odemolliens** [comment]
Please remove my email

**Comment by fpg1503** [comment]
@odemolliens sorry, I just posted the script output, I've removed it

**Comment by paulirish** [comment]
ah.. check the 2nd sentence [from here](https://developer.github.com/v3/users/#get-a-single-user):

> Note: The returned email is the user's publicly visible email address (or null if the user has not specified a public email address in their profile). The publicly visible email address only displays for authenticated API users.

**Comment by paulirish** [comment]
PR up for this in #8
