### ISSUE TITLE
Email format, silent mode, and null suppression

### ISSUE THREAD

**Issue by ghost** [paulirish/github-email#9]
A few ideas to consider:

* Make curl operate in silent mode.
* Use jq to parse the data, rather than sed and grep.
* Format the email address to be compatible with most e-mail clients.
* Suppress `null` results.

For example:

```
#!/bin/bash
curl -s https://api.github.com/users/$1/events/public | \
  jq -r '.[] | select(.payload != null) | .payload | select(.commits != null) | .commits[].author | .name + " <" + .email + ">"' | \
  sort | uniq
```

**Comment by paulirish** [comment]
sound great! want to make a pull request?

**Comment by ghost** [comment]
See https://github.com/paulirish/github-email/pull/13, which includes:

* Passing GitHub API token as parameter to REST API calls
* Documentation simplifications to avoid duplication of instructional information
* Command-line argument passing POSIX-style, and other minor POSIX-compatibility changes
* Allow user to provide GitHub API token on the command line using the `-t` option
* Store GitHub API token in a file if the default `GITHUB_TOKEN` environment variable is missing
* Colour definitions
* Source formatting (replaced tabs with two spaces)
* Eliminated various duplicated code segments
* Changed "fade" to "warning"

**Comment by ghost** [comment]
PR #13 (https://github.com/paulirish/github-email/pull/13/commits/5adcd7d91c031f86ce067252ad4006ea3a0df607) now resolves this issue. Updates include:

* Check for required software (jq and curl)
* Standard name/email format
* Parse json using jq instead of sed
* Suppress printing empty/invalid results

Sample output:

![screenshot](https://user-images.githubusercontent.com/2131950/51410341-2a572f80-1b19-11e9-97db-ce8ea9b9b606.png)


Here's a before (right) and after (left) shot:

![before-after](https://user-images.githubusercontent.com/2131950/51410816-90908200-1b1a-11e9-8d35-901026c90dfa.png)
